### ISSUE TITLE
Error 1000 "DNS points to prohibited IP" when using next-intl with Cloudflare

### ISSUE THREAD

**Issue by ClooudNine** [amannn/next-intl#1124]
### Description

Hello everyone!
After implementing next-intl into my next.js application in production, I get a **1000 DNS points to forbidden IP** **error** when trying to log in to the site. As I understand it, the problem lies in the Middleware that next-intl provides. I tried disabling intlMiddleware and the site worked completely. I turned on intlMiddleware back, I'm facing this problem. I tried removing x-frowarded-for and cf-connecting-ip from headers as described in the Clodflare documentation, but nothing helped. I also noticed that the redirect works out and I already get the error itself, being in some locale. The application is deployed in the Coolify environment version 3.12.36. How can I fix this problem?

### Verifications

- [x] I've verified that the problem I'm experiencing isn't covered in [the docs](https://next-intl-docs.vercel.app/).
- [X] I've searched for similar, existing issues on GitHub and [Stack Overflow](https://stackoverflow.com/search?q=next-intl).
- [X] I've compared my app to [a working example](https://next-intl-docs.vercel.app/examples) to look for differences.

### Mandatory reproduction URL

https://github.com/ClooudNine/cloud-retainer

### Reproduction description

Steps to reproduce:
1. Open https://retainer.cloud site
2. See error 1000 DNS points to prohibited IP 

### Expected behaviour

I expect next-intl middleware not to cause 1000 DNS points to prohibited IP errors

**Comment by ClooudNine** [comment]
I fixed it! The problem was the incorrect use of two middleware (auth.js and next-intl) together. The branch helped in the solution https://github.com/amannn/next-intl/issues/596 . Thank you all!

**Comment by ClooudNine** [comment]
I fixed it! The problem was the incorrect use of two middleware (auth.js and next-intl) together. The branch helped in the solution https://github.com/amannn/next-intl/issues/596 . Thank you all!

**Comment by adilsonx** [comment]
Hello, I have the same error with the same setup (coolify + cloudflare). I tried the solution in #596 but still have the error :( (when returning the next-intl middleware in the next auth Middleware).

@ClooudNine Can I know how did you make it ? Thanks a lot.

Code : 

```js 

const authMiddleware = auth((req) => {
  ....
//auth stuff

  return intlMiddleware(req);
});


const middleware = (req: NextRequest) => {
 .....

  if (isPublicPage) {
    return intlMiddleware(req);
  } else {
    return (authMiddleware as any)(req);
  }
};

export const config = {
  matcher: ["/((?!_next|.*\\..+$).*)"],
};

export default middleware;

**Comment by suitux** [comment]
> I fixed it! The problem was the incorrect use of two middleware (auth.js and next-intl) together. The branch helped in the solution #596 . Thank you all!

This was the fix for me!

Thanks 😄
