### ISSUE TITLE
next-intl beta for Next 13 not redirect to base URL when default locale match

### ISSUE THREAD

**Issue by manujoz** [amannn/next-intl#210]
### Description

I have config defaultLocale in middleware.js but when a use Link component to change to default language always use language preffix instead base url

### Reproduction URL (CodeSandbox)

https://codesandbox.io/p/sandbox/modest-jang-1yhdgq?file=%2Fapp%2F%5Blocales%5D%2Fpage.js&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A8%7D%5D

### Reproduction description

- Open preview sandbox in new browser tab.
- Click link to change language to english
- Click link to change language to spanish

### Expected behaviour

When to change to english (is not default locale) the url is **https://xxxx:3000/en**, but when you change again to spanish (default language) the url si **http://xxxx:3000/es**, when the correct behaviour could must be **http://xxxx:3000**

**Comment by amannn** [comment]
Thanks for the report! I made a note of this in https://github.com/amannn/next-intl/pull/149 and will look into it!

**Comment by amannn** [comment]
This is fixed in `2.12.0-beta.3`!

**Comment by gkielwasser** [comment]
> This is fixed in `2.12.0-beta.3`!

@amannn I'm using `next-intl@2.19.0` and this issue is still occuring

default locale: 'fr'

From page: `/blog`
`<Link href="/blog" locale="fr"/>` 
href is '/blog' ( Valid )

From page: `/en/blog`
`<Link href="/blog" locale="fr"/>` 
href is '/fr/blog' ( Invalid )
