### ISSUE TITLE
Using all the Steps in the Docs yet I still see the same error "Error: Couldn't find next-intl config file. Please follow the instructions"

### ISSUE THREAD

**Issue by EfstathiadisD** [amannn/next-intl#639]
### Description

I am using the latest release of `next-intl`. I was previously using 2.x and was working fine. I did all the Steps described in this [page](https://next-intl-docs.vercel.app/docs/getting-started/app-router) as the error message suggests.

Here are the files I have:
```src/middleware.ts
import createI18nMiddleware from "next-intl/middleware";

export default createI18nMiddleware({
	locales: ["en", "el", "de"],
	defaultLocale: "en",
});

export const config = {
	matcher: ["/", "/((?!api|_next|.*\\..*).*)"],
};
```

```src/i18n.ts

import { getRequestConfig } from "next-intl/server";

export default getRequestConfig(async ({ locale }) => ({
	messages: (await import(`../locales/${locale}.json`)).default,
}));
```

```next.config.cjs
const { withSentryConfig } = require("@sentry/nextjs");
const withNextIntl = require('next-intl/plugin')();
const path = require("path");

/** @type {import('next').NextConfig} */
const nextConfig = {
	pageExtensions: ["ts", "tsx"],
	compiler: {
		emotion: true,
	},
	experimental: {
		esmExternals: true,
		externalDir: true,
	},
	sentry: {
		disableServerWebpackPlugin: true,
		disableClientWebpackPlugin: true,
	},
	transpilePackages: [
		"@***/components/*",
		"@***/constants/*",
		"@***/cookies/*",
		"@***/theme/*",
		"@***/utils/*",
	],
};

module.exports = withSentryConfig(withNextIntl(nextConfig), {
	org: "****",
	project: "***",
	authToken: process.env.SENTRY_AUTH_TOKEN,

	disableLogger: true,
	hideSourceMaps: true,
	transpileClientSDK: true,
});
```

```src/app/page.tsx

import { redirect } from "next/navigation";

export default function RootPage() {
	redirect("/en");
}
```

```src/app/layout.tsx
import "./globals.css";

import type { PropsWithChildren } from "react";

type RootLayoutProps = PropsWithChildren<Record<string, never>>;

function RootLayout({ children }: RootLayoutProps) {
	return children;
}

export default RootLayout;
```

```src/app/[locale]/layout.tsx
import type { PropsWithChildren } from "react";

import { Inter } from "next/font/google";
import { notFound } from "next/navigation";

import { NextIntlClientProvider } from "next-intl";
import { getTranslations, unstable_setRequestLocale } from "next-intl/server";

import { ThemeProvider } from "@midgard/components/ThemeProvider/ThemeProvider";

import { getMessages } from "../../clients/i18n";
import { ApolloProvider } from "../../components/ApolloProvider";

const ALL_LOCALES = ["en", "el", "de"];
const inter = Inter({ subsets: ["latin", "greek"], display: "swap" });

type LocaleLayoutProps = PropsWithChildren<{
	params: { locale: string };
}>;

export function generateStaticParams() {
	return ALL_LOCALES.map((locale) => ({ locale }));
}

export async function generateMetadata({ params }: LocaleLayoutProps) {
	const t = await getTranslations({ locale: params.locale });

	return {
		title: t("LOCALE.METADATA.TITLE"),
		description: t("LOCALE.METADATA.DESCRIPTION"),
	};
}

async function LocaleLayout({ children, params }: LocaleLayoutProps) {
	if (!ALL_LOCALES.includes(params.locale)) {
		return notFound();
	}

	const messages = await getMessages(params.locale);

	unstable_setRequestLocale(params.locale);

	return (
		<html suppressHydrationWarning={true} lang={params.locale}>
			<head>
				<meta
					name="format-detection"
					content="telephone=no, date=no, email=no, address=no"
				/>
				<meta name="color-scheme" content="light dark" />
			</head>
			<body suppressHydrationWarning className={inter.className}>
				<ApolloProvider>
					<NextIntlClientProvider messages={messages}>
						<ThemeProvider>{children}</ThemeProvider>
					</NextIntlClientProvider>
				</ApolloProvider>
			</body>
		</html>
	);
}

export default LocaleLayout;
```

And it should theoretically work. I deleted `node_modules`, disabled other middleware removed Sentry in case it conflicted somewhere, yet nothing.

The issue seems to be with the matcher. With the one you are providing all my routes are 404, and with the one that matches mine, throw the above error.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-26fy8s?file=%2Fsrc%2Fmiddleware.ts%3A7%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp1ml0um00093b5xtznwcm9y%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp1ml0ul00033b5xh3pzt6ve%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp1ml0ul00063b5xts0ianf5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp1ml0um00083b5xw5ej96sc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp1ml0ul00033b5xh3pzt6ve%2522%253A%257B%2522id%2522%253A%2522clp1ml0ul00033b5xh3pzt6ve%2522%252C%2522activeTabId%2522%253A%2522clp1mlcsd005z3b5x4vv5w82n%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp1ml0ul00023b5xfqsqtbgb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmiddleware.ts%2522%252C%2522id%2522%253A%2522clp1mlcsd005z3b5x4vv5w82n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp1ml0um00083b5xw5ej96sc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp1ml0um00073b5xm5bawiod%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%252C%2522id%2522%253A%2522clp1ml0um00083b5xw5ej96sc%2522%252C%2522activeTabId%2522%253A%2522clp1ml0um00073b5xm5bawiod%2522%257D%252C%2522clp1ml0ul00063b5xts0ianf5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp1ml0ul00043b5xuwzh19r6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp1ml0ul00053b5x4xs7m1qa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clp1ml0ul00063b5xts0ianf5%2522%252C%2522activeTabId%2522%253A%2522clp1ml0ul00043b5xuwzh19r6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. See error: … 

The error stems from the path matcher. In real project, we might have more complicated stuff. What should we use then? Is it a bug in `next-intl`?

### Expected behaviour

When I use a matcher, it should match the routes we have in our applications and not show 404, and should be able to use next-intl as well.

**Comment by amannn** [comment]
I think your matcher is off and doesn't match `/en`. 

The matcher that [the docs suggest for `localePrefix: 'as-needed'`](https://next-intl-docs.vercel.app/docs/routing/middleware#matcher-no-prefix) works for me in your CodeSandbox ([fixed version](https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-jf44dw?file=%2Fsrc%2Fmiddleware.ts%3A10%2C50)). If you need something more specialized, make sure that it matches all relevant pathnames in your app.

Hope this helps!

**Comment by amannn** [comment]
Closing this due to inactivity.

**Comment by EfstathiadisD** [comment]
Sorry for this, but I tried a brand new repo. Copying one to one from the `examples` file on you repo. It just doesn't work. I am not sure what the problem is. It just doesn't work. The code is the same, I even copied the pathnames strategy to be sure.

What am I doing wrong? The error keeps saying it cannot find the `next-intl` config. Where is that config? The main diff with the examples I see, is I need the `NextIntlClientProvider`. The examples don't use it. So, they don't pass it the messages. Any help would be appreciated. I can even invite you for a bit on the private repo.

Or even a simple example that has the NextIntlClientProvider and something close to my setup would be great. Thank you in advance..

**Comment by EfstathiadisD** [comment]
Here is an example. It is 1-2-1 what you have in the examples. Can you take a look please? I am sure it should be working. What am I doing wrong?

**Comment by CrazyOrr** [comment]
Change your `next.config.cjs` to `next.config.js` should fix it. Took me a long time to figure this out too.

**Comment by lhguerra** [comment]
I'm not using cjs but still get the same issue. The docs are very confusing, the client way of setting up aks for no next.config alterations and also no special config files are needed. But it is impossible to make it work without ir.

**Comment by eyedol** [comment]
> Change your `next.config.cjs` to `next.config.js` should fix it. Took me a long time to figure this out too.

I faced a similar issue. I changed mine from `next.config.ts` to `next.config.js` and it's the only way it worked. Though all the examples uses a `next.config.ts` makes me curious why it doesn't work with `next.config.ts`

**Comment by Firouzzadeh99** [comment]
That didn’t work for me, but changing the file to `next.config.mjs` (instead of `.ts`) solved the issue. Hope it helps someone!

**Comment by radiophp** [comment]
> That didn’t work for me, but changing the file to `next.config.mjs` (instead of `.ts`) solved the issue. Hope it helps someone!

what is happening ! i have change .mjs to .ts and my problem was resolved :))

**Comment by hamudeshahin** [comment]
@Firouzzadeh99 @radiophp both of `.mjs` and `.ts` not worked for me :)

**Comment by ahkhanjani** [comment]
In case you are using stable Turbopack, it seems like as of now, next-intl is using the experimental turbo config to do turbo stuff. It tries to inject the config into `config.experimental.turbo`. But stable Turbopack uses `config.turbopack`. You need to move the turbo config into the correct object.

```ts
import type { NextConfig } from "next";
import type { TurbopackOptions } from "next/dist/server/config-shared";
import createNextIntlPlugin from "next-intl/plugin";

const config: NextConfig = {
  experimental: {
    turbopackFileSystemCacheForDev: true,
    authInterrupts: true,
  },

  reactCompiler: true,
  cacheComponents: true,

  turbopack: {
     // Whatever config you have here.
  },
};

// Get the experimental config object
const experimental = finalDamnConfig.experimental as { turbo?: TurbopackOptions };
// Move the next-intl turbo config into the stable version
finalDamnConfig.turbopack = {
  ...finalDamnConfig.turbopack,
  ...(experimental?.turbo ?? {}),
};
// Optionally delete the old turbo config to get rid of the console warning for the key not existing
delete experimental.turbo;

export default finalDamnConfig;
```

**Comment by DrKaoliN** [comment]
I fixed this by double checking my `next.config.ts` file. In my case I was exporting `NextConfig` twice.

**Comment by chienhsiang-hung** [comment]
> Change your `next.config.cjs` to `next.config.js` should fix it. Took me a long time to figure this out too.

worked magically

**Comment by stevanstojanovic93** [comment]
In my case I fixed it like this:

```
// next.config.ts
import { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const nextConfig: NextConfig = {};

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");
export default withNextIntl(nextConfig);
```

```
// src/middleware.ts
import createMiddleware from "next-intl/middleware";
import { routing } from "./i18n/routing";

export default createMiddleware(routing);

export const config = {
  // Match all pathnames except for
  // - … if they start with `/api`, `/trpc`, `/_next` or `/_vercel`
  // - … the ones containing a dot (e.g. `favicon.ico`)
  matcher: "/((?!api|trpc|_next|_vercel|.*\\..*).*)",
};
```
```
// src/i18n/routing.ts
import { DEFAULT_LOCALE, LOCALES } from "@/src/i18n/locale";
import { defineRouting } from "next-intl/routing";

export const routing = defineRouting({
  // A list of all locales that are supported
  locales: LOCALES,

  // Used when no locale matches
  defaultLocale: DEFAULT_LOCALE,
});
```

```
// src/i18n/request.ts
import { getRequestConfig } from "next-intl/server";
import { resolveLocale } from "./locale";

export default getRequestConfig(async ({ requestLocale }) => {
  // requestLocale comes from the URL segment (e.g. /sr/... → "sr")
  const requested = await requestLocale;
  const locale = resolveLocale(requested);

  return {
    locale,
    messages: (await import(`../../messages/${locale}.json`)).default,
  };
});
```

```
// src/i18n/locales.ts
export const LOCALES = ["en", "sr"] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = "en";

export function resolveLocale(locale: string | undefined): Locale {
  if (locale && LOCALES.includes(locale as Locale)) {
    return locale as Locale;
  }
  return DEFAULT_LOCALE;
}
```

```
// app/[locale]/layout.tsx
import type { Metadata } from "next";

import { ThemeProvider } from "../../components/providers/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LOCALES, resolveLocale } from "@/src/i18n/locale";

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const siteUrl = ";

  const titles = {
    sr: "",
    en: "",
  };

  const descriptions = {
    sr: "",
    en: "",
  };

  const title = titles[locale as keyof typeof titles] || titles.en;
  const description =
    descriptions[locale as keyof typeof descriptions] || descriptions.en;

  return {
    title,
    description,
    keywords: [],
    authors: [{ name: "" }],
    creator: "",
    publisher: "",
    openGraph: {
      type: "",
      locale: locale,
      url: `${siteUrl}/${locale}`,
      siteName: "",
      title,
      description,
      images: [
        {
          url: `${siteUrl}/og-image.png`,
          width: 1200,
          height: 630,
          alt: "",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${siteUrl}/og-image.png`],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    verification: {
      google: "your-google-verification-code",
    },
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale: localeParam } = await params;
  const locale = resolveLocale(localeParam);
  const messages = await getMessages();

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem={false}
        disableTransitionOnChange={false}
      >
        {children}
      </ThemeProvider>
    </NextIntlClientProvider>
  );
}
```

and ofc rootOfTheProject/messages/en.json

packages versions are:

1. React 19
2. NextJS 16
3. Node 22

Hopefully someone finds this usefull
