### ISSUE TITLE
Turbo and messages imports

### ISSUE THREAD

**Issue by markomitranic** [amannn/next-intl#898]
### Description

Turbo doesn't seem to work with dynamically importing messages files. Basically it always loads the first file in the folder.

This is not a `next-intl` issue, but a Turbo issue instead. I am opening this thread with the goal of tracking the corresponding issues in the Turbo repository, and preventatively providing more information on this for future readers.

Update: I have found that finding Turbo issues on this is actually quite hard. @amannn have you seen any?

### Mandatory reproduction URL

https://github.com/markomitranic/dynamic-turbo-imports

### Reproduction description

Read the repository Readme, it contains steps. In short:
- `npm run dev` - will show different languages on different locales
- `npm run turbo` - will show the contents of /messages/_notUsed.json which is not referenced to anywhere in the code.

<img width="1473" alt="Screenshot 2024-02-28 at 09 26 34" src="https://github.com/amannn/next-intl/assets/10811624/ee59f894-ad97-42ce-b314-5823a2d6e6be">
<img width="1473" alt="Screenshot 2024-02-28 at 09 30 56" src="https://github.com/amannn/next-intl/assets/10811624/d9eaa9cd-2f5e-4d2c-a272-bacc89a5746e">

### Expected behaviour

Should show different, and appropriate languages when using turbo.

**Comment by amannn** [comment]
Yep, I ran into this too: https://github.com/amannn/next-intl/issues/718#issuecomment-1856252053, see also: https://github.com/vercel/next.js/issues/56531.

 It seems like [there's some progress being made in this area](https://github.com/vercel/next.js/issues/56531#issuecomment-1927533401), so hopefully this gets resolved soon.

We can leave this open for now until the bug is resolved upstream!

**Comment by Yohannfra** [comment]
> Yep, I ran into this too: [#718 (comment)](https://github.com/amannn/next-intl/issues/718#issuecomment-1856252053), see also: [vercel/next.js#56531](https://github.com/vercel/next.js/issues/56531).
> 
> It seems like [there's some progress being made in this area](https://github.com/vercel/next.js/issues/56531#issuecomment-1927533401), so hopefully this gets resolved soon.
> 
> We can leave this open for now until the bug is resolved upstream!

It looks like this bug has been resolved upstream for some times now. Maybe this issue can be closed now.

**Comment by amannn** [comment]
That's also my impression, thanks for leaving a note here @Yohannfra!

**Comment by kevinrss01** [comment]
I still have the issue here. Some texts are not translated. I have the issue only with Turbopack activated.
