### ISSUE TITLE
[Docs]: Navigation APIs

### ISSUE THREAD

**Issue by MohammadSeyedabadi** [amannn/next-intl#948]
### Link to page

https://next-intl-docs.vercel.app/docs/routing/navigation#shared-pathnames

### Describe the problem

Hi. I think it is good to change the following code in middleware.ts from this:
```js
import createMiddleware from 'next-intl/middleware';
import {locales, localePrefix} from './navigation';
 
export default createMiddleware({
  defaultLocale: 'en',
  localePrefix,
  locales
});
```
to this:
```js
import createMiddleware from 'next-intl/middleware';
import {locales, localePrefix} from './navigation';
 
export default createMiddleware({
  defaultLocale: 'en',
  localePrefix,
  locales
});
//////////////////////////
export const config = {
  // Match only internationalized pathnames
  matcher: ['/', '/(fa|en)/:path*']
};
//////////////////////////
```

if you don't write the piece of code i separated with slashes, the code would not work.

And in https://next-intl-docs.vercel.app/docs/routing/navigation#localized-pathnames apparently I can't use farsi characters,
something like:
```js
'/about': {
    en: '/about',
    fa: '/درباره-من'
  },
```
and if i do so, i will get a 404 error. Is there fix for this?

**Comment by amannn** [comment]
That's a good point, thanks for the report! I've adapted this in https://github.com/amannn/next-intl/commit/ad07a57bf503bb7d4870741fde71eab22b21030d and added an ellipsis to the middleware code samples that are incomplete, indicating that the developer should leave other logic from that file in place.

The issue with localized pathnames that you've mentioned is discussed here: https://github.com/amannn/next-intl/issues/607. I haven't had time to look into this yet, but contributions are welcome in case you'd be interested.

**Comment by sahandsn** [comment]
any update on the issue?

**Comment by MohammadSeyedabadi** [comment]
> any update on the issue?

This problem has been fixed in new updates.

**Comment by sahandsn** [comment]
although links are correct, when i generate sitemap, i still see wrong encoded strings

**Comment by MohammadSeyedabadi** [comment]
I don't have this problem. Can you take a screenshot so I can see exactly what you're seeing?
Personally, I get my sitemap information from the database and I don't see how this could be a problem with the next-intl package.
By the way i'm using "next-intl": "^3.23.2"

**Comment by edward-meister** [comment]
"next": "15.4.3",
"next-intl": "^4.3.4",

<img width="986" height="393" alt="Image" src="https://github.com/user-attachments/assets/9596fe4b-75cf-46f6-bb91-16bdaef1882f" />

sitemap.ts
```
import { MetadataRoute } from "next";
import { sitemapBuilder, SitemapLinks } from "@/sitemapUtils";


export default function sitemap(): MetadataRoute.Sitemap {
  const links: SitemapLinks = [
    {
      href: "/",
      priority: 1.0,
    },
    { href: "/not-found", priority: 0.1 },
  ];

  return sitemapBuilder(links);
}
```


routing.ts
```
import { defineRouting } from "next-intl/routing";
import routes from "@/routes";

export type TDirection = "rtl" | "ltr";
export type TLocale = "en" | "de" | "fa";
interface ILocaleItem {
  key: TLocale;
  title: string;
  direction: TDirection;
}

export const ENGLISH: ILocaleItem = {
  key: "en",
  title: "English",
  direction: "ltr",
} as const;
export const GERMAN: ILocaleItem = {
  key: "de",
  title: "Deutsche",
  direction: "ltr",
} as const;
export const FARSI: ILocaleItem = {
  key: "fa",
  title: "فارسی",
  direction: "rtl",
} as const;

export const locales = [ENGLISH, GERMAN, FARSI] as const;
export const localeKeys = locales.map((locale) => locale.key);
export const defaultLocale = FARSI;
export const pathnames = {
  [routes.root]: routes.root,
  [routes.notFound]: {
    [ENGLISH.key]: routes.notFound,
    [GERMAN.key]: "/nicht-gefunden",
    [FARSI.key]: "/یافت-نشد",
  },
};

export const routing = defineRouting({
  locales: localeKeys,
  defaultLocale: defaultLocale.key,
  pathnames: pathnames,
  localePrefix: "as-needed",
});
```

sitemapUtils.ts
```
import { MetadataRoute } from "next";
import { Locale } from "next-intl";
import { getPathname } from "@/i18n/navigation";
import { defaultLocale, routing } from "@/i18n/routing";
import { TInternalLink } from "@/types/general";
import { env } from "@/env/client";

export type SitemapLinks = {
  href: TInternalLink;
  priority: number;
  lastModified?: Date;
}[];

export function sitemapBuilder(arr: SitemapLinks): MetadataRoute.Sitemap {
  return arr.map(({ href, priority, lastModified }) => {
    return getEntries(href, priority, lastModified);
  });
}

function getEntries(
  href: TInternalLink,
  priority: number,
  lastModified?: Date,
): MetadataRoute.Sitemap[number] {
  return {
    url: getUrl(href, defaultLocale.key),
    lastModified: lastModified ?? new Date(),
    changeFrequency: "monthly",
    priority,
    alternates: {
      languages: Object.fromEntries(
        routing.locales.map((cur) => [cur, getUrl(href, cur)]),
      ),
    },
  };
}

function getUrl(href: TInternalLink, locale: Locale) {
  const pathname = getPathname({ locale, href });
  return new URL(pathname, env.NEXT_PUBLIC_ROOT_URL).href;
}

```

**Comment by MohammadSeyedabadi** [comment]
it is because of the new URL(). you can use strings instead and i guess it would fix your problem. i don't know why you use new URL() in the first place, but you can do a research on whether or not to use it

**Comment by edward-meister** [comment]
from what i can see, getPathname return value is distorted, regadless whether I use new URL() or not.

```
import { MetadataRoute } from "next";
import { Locale } from "next-intl";
import { getPathname } from "@/i18n/navigation";
import { defaultLocale, routing } from "@/i18n/routing";
import { TInternalLink } from "@/types/general";
import { env } from "@/env/client";

export type SitemapLinks = {
  href: TInternalLink;
  priority: number;
  lastModified?: Date;
}[];

export function sitemapBuilder(arr: SitemapLinks): MetadataRoute.Sitemap {
  return arr.map(({ href, priority, lastModified }) => {
    return getEntries(href, priority, lastModified);
  });
}

function getEntries(
  href: TInternalLink,
  priority: number,
  lastModified?: Date,
): MetadataRoute.Sitemap[number] {
  return {
    url: getUrl(href, defaultLocale.key),
    lastModified: lastModified ?? new Date(),
    changeFrequency: "monthly",
    priority,
    alternates: {
      languages: Object.fromEntries(
        routing.locales.map((cur) => [cur, getUrl(href, cur)]),
      ),
    },
  };
}

function getUrl(href: TInternalLink, locale: Locale) {
  const pathname = getPathname({ locale, href });
  const newHref = new URL(pathname, env.NEXT_PUBLIC_ROOT_URL).href;
  console.log("url", href, pathname, newHref);
  return newHref;
}

```

log output in terminal
```
url / / http://localhost:3000/
url / /en http://localhost:3000/en
url / /de http://localhost:3000/de
url / / http://localhost:3000/
url /not-found /%DB%8C%D8%A7%D9%81%D8%AA-%D9%86%D8%B4%D8%AF http://localhost:3000/%DB%8C%D8%A7%D9%81%D8%AA-%D9%86%D8%B4%D8%AF
url /not-found /en/not-found http://localhost:3000/en/not-found
url /not-found /de/nicht-gefunden http://localhost:3000/de/nicht-gefunden
url /not-found /%DB%8C%D8%A7%D9%81%D8%AA-%D9%86%D8%B4%D8%AF http://localhost:3000/%DB%8C%D8%A7%D9%81%D8%AA-%D9%86%D8%B4%D8%AF
```

however issue was resolved with decodeURIComponent
```
function getUrl(href: TInternalLink, locale: Locale) {
  const pathname = getPathname({ locale, href });
  const newHref = new URL(pathname, env.NEXT_PUBLIC_ROOT_URL).href;
  return decodeURIComponent(newHref);
}
```
